### ISSUE TITLE
Redirect output to a specific file.

### ISSUE THREAD

**Issue by nethomas1968** [DrBluefall/journalpp#1]
Hi,

I'm looking to incorporate your journald logging class in my homebrew projects.
I see that it works, and I see my messages appear in "journalctl -f" OK.

For example, this line appears:
Jun 14 14:14:05 C-NT-N850NG JournaldLoopTes[226027]: message sent from JournaldLoopTest: loopCount = 138

I would like to, somehow, redirect all lines from the JournalLoopTest program to a separate file. Maybe a file called /tmp/JournalLoopTest.log 

Is this something that can be done by tweaking journalctl, or would it need a change to this package ?

**Comment by SystemNeoSpl** [comment]
Well, I don't see why you couldn't do `journalctl -f > /tmp/JournalLoopTest.log`.

Also, full disclosure, I haven't exactly worked on this project in a while, but if you want to use it, I'd be happy to pick it back up and support it again.

**Comment by nethomas1968** [comment]
Hi, thanks for the response.
I did actually find another way of doing it. It means messing with the syslog configuration. If, for example, I have a small app called LoopTest, which uses your journalpp.h and lib.cpp files, then I get logging in this format:

Jun 14 16:23:10 C-NT-N850NG LoopTest[234350]: message sent from LoopTest: loopCount = 536

And, if I add this line to the bottom of /etc/rsyslog.conf:

:programname, isequal, "LoopTest" /var/log/custom.log

Then the logging comes out the new /var/log/custom.log file as I hoped it would.

So, it's all good. 
Thanks :)
